export const menuList = [
    {
        id: 1,
        name: "Личный кабинет",
        value: "account",
    },
    {
        id: 2,
        name: "Конвертировать файлы",
        value: "convert",
    },
    {
        id: 3,
        name: "Сохраненные файлы",
        value: "files",
    },
    {
        id: 4,
        name: "Статистика",
        value: "statistic",
    },
];

export const userData = {
    name: 'Даниил Суворов',
    email: 'eo18622@yandex.ru',
    status: 'участник',
    unit: 'ВП',
}

export const userUploadFiles = [
    {
        name: 'Документ 1',
        description: 'Первый тестовый документ',
        size: '1.5 MB',
        type: 'PDF',
        uploadTime: '10:30 17/07/2024',
        converted: true,
    },
    {
        name: 'Изображение 1',
        description: 'Тестовое изображение высокого качества',
        size: '3.2 MB',
        type: 'JPEG',
        uploadTime: '11:15 17/07/2024',
        converted: false,
    },
    {
        name: 'Видео 1',
        description: 'Тестовое видео файл',
        size: '20 MB',
        type: 'MP4',
        uploadTime: '12:00 17/07/2024',
        converted: true,
    },
    {
        name: 'Документ 2',
        description: 'Второй тестовый документ',
        size: '2.5 MB',
        type: 'DOCX',
        uploadTime: '12:45 17/07/2024',
        converted: true,
    },
    {
        name: 'Аудио 1',
        description: 'Тестовый аудио файл',
        size: '5 MB',
        type: 'MP3',
        uploadTime: '13:30 17/07/2024',
        converted: false,
    },
    {
        name: 'Аудио 1',
        description: 'Тестовый аудио файл',
        size: '5 MB',
        type: 'MP3',
        uploadTime: '13:30 17/07/2024',
        converted: false,
    },
    // kfd
    {
        name: 'Аудио 1',
        description: 'Тестовый аудио файл',
        size: '5 MB',
        type: 'MP3',
        uploadTime: '13:30 17/07/2024',
        converted: false,
    },
    {
        name: 'Аудио 1',
        description: 'Тестовый аудио файл',
        size: '5 MB',
        type: 'MP3',
        uploadTime: '13:30 17/07/2024',
        converted: false,
    },
    {
        name: 'Аудио 1',
        description: 'Тестовый аудио файл',
        size: '5 MB',
        type: 'MP3',
        uploadTime: '13:30 17/07/2024',
        converted: false,
    },
    {
        name: 'Аудио 1',
        description: 'Тестовый аудио файл',
        size: '5 MB',
        type: 'MP3',
        uploadTime: '13:30 17/07/2024',
        converted: false,
    },
    {
        name: 'Аудио 1',
        description: 'Тестовый аудио файл',
        size: '5 MB',
        type: 'MP3',
        uploadTime: '13:30 17/07/2024',
        converted: false,
    },
    {
        name: 'Аудио 1',
        description: 'Тестовый аудио файл',
        size: '5 MB',
        type: 'MP3',
        uploadTime: '13:30 17/07/2024',
        converted: false,
    },
    {
        name: 'Аудио 1',
        description: 'Тестовый аудио файл',
        size: '5 MB',
        type: 'MP3',
        uploadTime: '13:30 17/07/2024',
        converted: false,
    },
    {
        name: 'Аудио 1',
        description: 'Тестовый аудио файл',
        size: '5 MB',
        type: 'MP3',
        uploadTime: '13:30 17/07/2024',
        converted: false,
    },
]